// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgvXHVHt913QNaYi3ZmhM6Ig2TcfweKzw',
    appId: '1:706866247395:web:09b1b5fd729e2db49577d6',
    messagingSenderId: '706866247395',
    projectId: 'insta-7d7a2',
    authDomain: 'insta-7d7a2.firebaseapp.com',
    storageBucket: 'insta-7d7a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamzAXa2CyK1iDIvcjUW9HhNO8Txxsc7Q',
    appId: '1:706866247395:android:340e284554c23db19577d6',
    messagingSenderId: '706866247395',
    projectId: 'insta-7d7a2',
    storageBucket: 'insta-7d7a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMx-G1XYiWPbRw6u9DACK9zst7sptuOis',
    appId: '1:706866247395:ios:9d8ce5348d2b22ba9577d6',
    messagingSenderId: '706866247395',
    projectId: 'insta-7d7a2',
    storageBucket: 'insta-7d7a2.appspot.com',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMx-G1XYiWPbRw6u9DACK9zst7sptuOis',
    appId: '1:706866247395:ios:9d8ce5348d2b22ba9577d6',
    messagingSenderId: '706866247395',
    projectId: 'insta-7d7a2',
    storageBucket: 'insta-7d7a2.appspot.com',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgvXHVHt913QNaYi3ZmhM6Ig2TcfweKzw',
    appId: '1:706866247395:web:b186cf9907ab129f9577d6',
    messagingSenderId: '706866247395',
    projectId: 'insta-7d7a2',
    authDomain: 'insta-7d7a2.firebaseapp.com',
    storageBucket: 'insta-7d7a2.appspot.com',
  );
}
